objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Claim_Approved_on__c</fullName>
        <label>Claim Approved on</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Claim_Status__c</fullName>
        <label>Claim Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/ElementSendClaimApprovedMail_Test.cls
@isTest
public class ElementSendClaimApprovedMail_Test{
     static testmethod void ProcessbatchForSendingEmails() {
         Element_TestDataUtil.getBulkContacts();
         system.assertEquals([select count() from contact],197);
         
         Test.startTest();
              Id batchId = Database.executeBatch(new Element_SendClaimApprovedMailToCustomer());
         Test.stopTest();
         AsyncApexJob EmailJob = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id =:batchId ];
         system.assert(EmailJob .status.toLowerCase()=='completed');
         system.assertEquals([select count() from contact where Claim_Status__c='Approved' and Claim_Approved_on__c=null],29);
     }  
}